# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "github-maverick"
license = "MIT"
licenselink = "https://github.com/y0ug/hugo-theme-github-maverick/blob/master/LICENSE"
description = "Theme that used github-markdown CSS to render blog post"
homepage = ""
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Hugo Caron"
  homepage = ""

# If porting an existing theme
[original]
  name = "Maverick"
  homepage = ""
  repo = "https://github.com/canhtran/maverick/"
